### ISSUE TITLE
Save property window

### ISSUE THREAD

**Issue by KathrinFausel** [inovex/attractify#38]
The user's entries/changes are automatically saved on all pages, so that the user no longer has to use a Save button

## Views:
- [x] Events
- [x] Contexts
- [x] Custom Traits
- [x] Computed Traits
- [x] Computed Traits (fix validation)
- [x] Audiences
- [x] Actions

## Todo's:
- [x] remove save button
- [x] save entries/ changes automatically
- [x] Show a banner, informing the user, that his changes were saved. For example with the text: "Your changes have been successfully saved."
